<?php

use App\Services\AuthApiService;
use function Livewire\Volt\state;

state([
    'email' => '',
    'password' => '',
    'snackbar' => ['type' => '', 'message' => ''],
]);

$submit = function () {

    // Validasi
    if (!$this->email || !$this->password) {
        // assign ke state 'snackbar' — Volt/Livewire akan mengirim ke frontend
        $this->snackbar = ['type' => 'error', 'message' => 'Email dan password wajib diisi'];
        return;
    }

    $response = AuthApiService::login($this->email, $this->password);

    // Login gagal
    if ($response->failed()) {
        $this->snackbar = ['type' => 'error', 'message' => $response->json('message') ?? 'Login gagal!'];
        return;
    }

    // Berhasil → simpan session
    session([
        'token' => $response->json('token'),
        'user' => $response->json('user'),
    ]);

    // Tampilkan snackbar sukses (opsional)
    $this->snackbar = ['type' => 'success', 'message' => 'Login berhasil, mengalihkan...'];

    // Redirect (Volt mendukung $this->redirect)
    $this->redirect('/home', navigate: true);
};
?>


<x-layouts.mobile title="Masuk">

    <!-- SNACKBAR: entangle ke state Livewire 'snackbar' -->
    <div x-data="{
        snackbar: @entangle('snackbar'),
        show: false,
        _timeout: null,
        icons: { error: '⚠', success: '✔' },
        styles: {
            error: 'bg-red-500 text-white',
            success: 'bg-green-600 text-white'
        },
        showAndAutoHide() {
            if (!this.snackbar || !this.snackbar.message) return;
            this.show = true;
            if (this._timeout) clearTimeout(this._timeout);
            this._timeout = setTimeout(async () => {
                this.show = false;
                this._timeout = null;
                // clear snackbar back on server so state tetap bersih
                if (window.Livewire) {
                    // @this refers to Livewire component instance in frontend
                    // gunakan Livewire.find(...) jika perlu; @this.set tersedia jika Livewire >= versi tertentu
                    try {
                        // preferred: gunakan @this.set() generated by Livewire
                        @this.set('snackbar', { type: '', message: '' });
                    } catch (e) {
                        // fallback: gunakan Livewire.emit untuk memberitahu server (jika ada listener)
                        Livewire.emit('clearSnackbar');
                    }
                }
            }, 2500);
        }
    }" x-init="
        // watch perubahan pada entangled snackbar
        $watch('snackbar', value => {
            if (value && value.message) showAndAutoHide();
        }, { immediate: true });
    " x-show="show" x-cloak x-transition.opacity.duration.300ms
        class="fixed top-0 left-1/2 -translate-x-1/2 w-[390px] z-[9999] flex items-center gap-2 px-4 py-3 text-sm font-medium shadow-lg rounded-b-lg"
        :class="styles[snackbar?.type ?? 'success']">
        <span class="text-lg" x-text="icons[snackbar?.type ?? 'success']"></span>
        <span x-text="snackbar?.message ?? ''"></span>
    </div>


    <div class="relative w-full min-h-screen flex flex-col">

        {{-- Background --}}
        <img src="/images/assets/bg-pattern.png"
            class="absolute inset-0 w-full h-full object-cover pointer-events-none" />

        {{-- Content --}}
        <div class="relative z-10 px-6 pt-10">

            {{-- Back --}}
            <a href="/auth" class="text-white text-xl">&larr;</a>

            {{-- Logo --}}
            <div class="flex justify-center mt-4 mb-3">
                <img src="/images/assets/logo.png" class="w-20">
            </div>

            {{-- Card --}}
            <div class="bg-white/80 backdrop-blur-sm rounded-xl p-6 shadow-lg">

                <h1 class="text-center font-bold text-xl mb-4">Masuk</h1>

                {{-- EMAIL --}}
                <x-mobile.input wire:model.defer="email" placeholder="Email" type="email"
                    :invalid="$snackbar['type'] === 'error' && !$email" :errorMessage="$snackbar['type'] === 'error' && !$email ? 'Email wajib diisi' : null" />

                {{-- PASSWORD --}}
                <x-mobile.input wire:model.defer="password" placeholder="Password" type="password"
                    :invalid="$snackbar['type'] === 'error' && !$password" :errorMessage="$snackbar['type'] === 'error' && !$password ? 'Password wajib diisi' : null" />


                {{-- BUTTON LOGIN --}}
                <x-mobile.button class="mt-4" wire:click="submit">
                    Masuk Sekarang
                </x-mobile.button>

                {{-- FORGOT --}}
                <a href="/forgot-password">
                    <x-mobile.button hex="#E6E6E6" text="#50555C" class="mt-3">
                        Lupa Password
                    </x-mobile.button>
                </a>

                {{-- REGISTER --}}
                <p class="text-center text-sm mt-3 text-black">
                    Belum punya akun?
                    <a href="/register" class="text-green-700 font-semibold">Register disini</a>
                </p>

            </div>
        </div>

    </div>

</x-layouts.mobile>